spring.application.name=gestion-compte
management.endpoints.web.exposure.include=health,info,metrics,prometheus,mappings
management.endpoint.health.show-details=when-authorized
management.metrics.tags.application=gestion-compte
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000
logging.level.org.springframework.security=INFO
